"""
list of: stopwords, contracted forms 
"""

STOPWORDS = ['a', 'about', 'above', 'according', 'across',
              'after', 'afterwards', 'again', 'against',
              'albeit', 'all', 'almost', 'alone', 'along',
              'already', 'also', 'although', 'always',
              'am', 'among', 'amongst', 'an', 'and',
              'another', 'any', 'anybody', 'anyhow',
              'anyone', 'anything', 'anyway', 'anywhere',
              'apart', 'are', 'around', 'as', 'at', 'av',
              'be', 'became', 'because', 'become',
              'becomes', 'becoming', 'been', 'before',
              'beforehand', 'behind', 'being', 'below',
              'beside', 'besides', 'between', 'beyond',
              'both', 'but', 'by', 'can', 'cannot',
              'canst', 'certain', 'cf', 'choose',
              'contrariwise', 'cos', 'could', 'cu', 'day',
              'do', 'does', "doesn't", 'doing', 'dost',
              'doth', 'double', 'down', 'dual', 'during',
              'each', 'either', 'else', 'elsewhere',
              'enough', 'et', 'etc', 'even', 'ever',
              'every', 'everybody', 'everyone',
              'everything', 'everywhere', 'except',
              'excepted', 'excepting', 'exception',
              'exclude', 'excluding', 'exclusive', 'far',
              'farther', 'farthest', 'few', 'ff', 'first',
              'for', 'formerly', 'forth', 'forward',
              'from', 'front', 'further', 'furthermore',
              'furthest', 'get', 'go', 'had', 'halves',
              'hardly', 'has', 'hast', 'hath', 'have',
              'he', 'hence', 'henceforth', 'her', 'here',
              'hereabouts', 'hereafter', 'hereby',
              'herein', 'hereto', 'hereupon', 'hers',
              'herself', 'him', 'himself', 'hindmost',
              'his', 'hither', 'hitherto', 'how',
              'however', 'howsoever', 'i', 'ie', 'if',
              'in', 'inasmuch', 'inc', 'include',
              'included', 'including', 'indeed', 'indoors',
              'inside', 'insomuch', 'instead', 'into',
              'inward', 'inwards', 'is', 'it', 'its',
              'itself', 'just', 'kind', 'kg', 'km', 'last',
              'latter', 'latterly', 'less', 'lest', 'let',
              'like', 'little', 'ltd', 'many', 'may',
              'maybe', 'me', 'meantime', 'meanwhile',
              'might', 'moreover', 'most', 'mostly',
              'more', 'mr', 'mrs', 'ms', 'much', 'must',
              'my', 'myself', 'namely', 'need', 'neither',
              'never', 'nevertheless', 'next', 'no',
              'nobody', 'none', 'nonetheless', 'noone',
              'nope', 'nor', 'not', 'nothing',
              'notwithstanding', 'now', 'nowadays',
              'nowhere', 'of', 'off', 'often', 'ok', 'on',
              'once', 'one', 'only', 'onto', 'or', 'other',
              'others', 'otherwise', 'ought', 'our',
              'ours', 'ourselves', 'out', 'outside',
              'over', 'own', 'per', 'perhaps', 'plenty',
              'provide', 'quite', 'rather', 'really',
              'round', 'said', 'sake', 'same', 'sang',
              'save', 'saw', 'see', 'seeing', 'seem',
              'seemed', 'seeming', 'seems', 'seen',
              'seldom', 'selves', 'sent', 'several',
              'shalt', 'she', 'should', 'shown',
              'sideways', 'since', 'slept', 'slew',
              'slung', 'slunk', 'smote', 'so', 'some',
              'somebody', 'somehow', 'someone',
              'something', 'sometime', 'sometimes',
              'somewhat', 'somewhere', 'spake', 'spat',
              'spoke', 'spoken', 'sprang', 'sprung',
              'stave', 'staves', 'still', 'such',
              'supposing', 'than', 'that', 'the', 'thee',
              'their', 'them', 'themselves', 'then',
              'thence', 'thenceforth', 'there',
              'thereabout', 'thereabouts', 'thereafter',
              'thereby', 'therefore', 'therein', 'thereof',
              'thereon', 'thereto', 'thereupon', 'these',
              'they', 'this', 'those', 'thou', 'though',
              'thrice', 'through', 'throughout', 'thru',
              'thus', 'thy', 'thyself', 'till', 'to',
              'together', 'too', 'toward', 'towards',
              'ugh', 'unable', 'under', 'underneath',
              'unless', 'unlike', 'until', 'up', 'upon',
              'upward', 'upwards', 'us', 'use', 'used',
              'using', 'very', 'via', 'vs', 'want', 'was',
              'we', 'week', 'well', 'were', 'what',
              'whatever', 'whatsoever', 'when', 'whence',
              'whenever', 'whensoever', 'where',
              'whereabouts', 'whereafter', 'whereas',
              'whereat', 'whereby', 'wherefore',
              'wherefrom', 'wherein', 'whereinto',
              'whereof', 'whereon', 'wheresoever',
              'whereto', 'whereunto', 'whereupon',
              'wherever', 'wherewith', 'whether', 'whew',
              'which', 'whichever', 'whichsoever', 'while',
              'whilst', 'whither', 'who', 'whoa',
              'whoever', 'whole', 'whom', 'whomever',
              'whomsoever', 'whose', 'whosoever', 'why',
              'will', 'wilt', 'with', 'within', 'without',
              'worse', 'worst', 'would', 'wow', 'ye',
              'yet', 'yes', 'year', 'yippee', 'you', 'your',
              'yours', 'yourself', 'yourselves']

OTHER_STOPWORDS = []  # # # not useful

CONTRACTED_FORMS = {'i\'m': 'i am',
                     'you\'re': 'you are',
                     'he\'s': 'he is',
                     'she\'s': 'she is',
                     'we\'re': 'we are',
                     'it\'s': 'it is',
                     'isn\'t': 'is not',
                     'aren\'t': 'are not',
                     'they\'re': 'they are',
                     'there\'s': 'there is',
                     'wasn\'t': 'was not',
                     'weren\'t': ' were not',
                     'i\'ve': 'i have',
                     'you\'ve': 'you have',
                     'we\'ve': 'we have',
                     'they\'ve': 'they have',
                     'hasn\'t': 'has not',
                     'haven\'t': 'have not',
                     'you\'d': 'you had',
                     'he\'d': 'he had',
                     'she\'d': 'she had',
                     'we\'d': 'we had',
                     'they\'d': 'they had',
                     'doesn\'t': 'does not',
                     'don\'t': 'do not',
                     'didn\'t': 'did not',
                     'i\'ll': 'i will',
                     'you\'ll': 'you will',
                     'he\'ll': 'he will',
                     'she\'ll': 'she will',
                     'we\'ll': 'we will',
                     'they\'ll': 'they will',
                     'there\'ll': 'there will',
                     'i\'d': 'i would',
                     'it\'d': 'it would',
                     'there\'d': 'there had',
                     'there\'d': 'there would',
                     'can\'t': 'can not',
                     'couldn\'t': 'could not',
                     'daren\'t': 'dare not',
                     'hadn\'t': 'had not',
                     'mightn\'t': 'might not',
                     'mustn\'t': 'must not',
                     'needn\'t': 'need not',
                     'oughtn\'t': 'ought not',
                     'shan\'t': 'shall not',
                     'shouldn\'t': 'should not',
                     'usedn\'t': 'used not',
                     'won\'t': 'will not',
                     'wouldn\'t': 'would not',
                     'what\'s': 'what is',
                     'that\'s': 'that is',
                     'who\'s': 'who is'}

if __name__ == '__main__':
    pass
